/* eslint-disable */
export default {
  return_game: '返回游戲',
  player: '玩家',
  get_price: '獲獎',
  bet_num: '投幣 {num}',
  no_data: '暫時沒有記錄',
  bet_record: '投幣記錄',
  round_title: 'No. {num}',
  price: '中獎: 0',
  price_num: '中獎 {num}',
  my_bet: '我：{num}',
  dog_win: '狗勝',
  cat_win: '貓勝',
  draw: '平局',
  fish_total: '魚總數：{num}',
  round_hash: '本局哈希：{hash}',
  hash_code: '哈希值：{hash}',
  copy: '複製',
  paste: '粘貼',
  bet_title: '我的投幣',
  settle: '結算',
  verify: '驗證',
  declare_verify:
    '我們確保所有的數據都是公平的；你可以隨時輸入哈希 來查詢對應的遊戲結果（不包含投幣返獎結果）',
  setting_voice: '音量設置',
  music: '音樂',
  sound: '音效',
  play: '開始遊戲',
  view_trend: '走勢',
  guess_winner: '猜勝負',
  guess_number: '猜數字',
  winner_subject: '請選擇您要支持的一方，為他加油吧！',
  number_subject: '請選擇雙方釣魚總數或區間！',
  guide_tips_1: '1. 選擇幣種',
  guide_tips_2: '2. 選擇投幣金額，投幣給您認為會獲勝的一方。',
  guide_tips_3: '3. 若您投幣的一方與獲勝一方相同，您將獲得對應獎勵。',
  error_1: '很抱歉，服務器異常，您可以稍後刷新重試',
  error_2: '賬戶餘額不足',
  error_31: '房間維護中',
  error_32: '未登錄，請重新登錄',
  error_34_1: '戲未開始，不能投幣',
  error_36: '押注金額超出上限',
  copy_success: '複製成功',
  tips_hash_code: '雜湊值輸入錯誤，無法查詢',
  tips_paste: '長按粘貼',
  tips_net_timeout: '網絡異常，請重試',
  error_34: '投幣已結束',
  tips: '提示',
  error_34_0: '戲未開始，不能投幣',
  error_39: '投幣數量已達上限',
  msg_repeatedly_login: '您的賬號已在其他設備登錄',
  confirm: '確認',
  login: '登錄',
  login_to_view: '登錄查看',
  error_1_: '系統維​​護中',
  error_34_: '戲未開始，不能投幣',
  error_33: '你的操作太频繁了',
  error_37: '房間準備中，請稍後',
  no_search_data: '無記錄',
  error_3: '賬戶餘額不足',
  trend_tab_1: '勝負走勢',
  trend_tab_2: '總數走勢',
  recently_recorded: '顯示最近50條記錄',
};
