export const COMM_ASSETS = [{ url: 'atlas/alert.atlas', type: 'atlas' }];

export const LOADING_ASSETS = [
  { url: `loading/ani/loading.sk`, type: 'arraybuffer' },
  { url: `loading/ani/loading0.png`, type: 'image' },
  { url: `loading/ani/loading1.png`, type: 'image' },
  { url: `loading/ani/loading2.png`, type: 'image' },
  { url: `loading/ani/loading3.png`, type: 'image' },
  { url: `loading/ani/loading4.png`, type: 'image' },
  { url: `loading/ani/loading5.png`, type: 'image' },
  { url: `loading/ani/loading6.png`, type: 'image' },
];

export const GAME_ASSET = [
  { url: `game/ani/game_back.sk`, type: 'arraybuffer' },
  { url: `game/ani/game_back0.png`, type: 'image' },
  { url: `game/ani/game_back1.png`, type: 'image' },
  { url: `game/ani/game_back2.png`, type: 'image' },
  { url: `game/ani/game_back3.png`, type: 'image' },

  { url: `game/ani/game_front.sk`, type: 'arraybuffer' },
  { url: `game/ani/game_front0.png`, type: 'image' },
  { url: `game/ani/game_front1.png`, type: 'image' },
  { url: `game/ani/game_front2.png`, type: 'image' },
  { url: `game/ani/game_front3.png`, type: 'image' },
  { url: `game/ani/game_front4.png`, type: 'image' },

  { url: `game/ani/loadingIcon.sk`, type: 'arraybuffer' },
  { url: `game/ani/loadingIcon.png`, type: 'image' },
  { url: `roles/ani/cat.sk`, type: 'arraybuffer' },
  { url: `roles/ani/cat.png`, type: 'image' },
  { url: `roles/ani/cat.sk`, type: 'arraybuffer' },
  { url: `roles/ani/cat.png`, type: 'image' },
  { url: `roles/ani/dog.sk`, type: 'arraybuffer' },
  { url: `roles/ani/dog.png`, type: 'image' },
  { url: `fishes/ani/splash.sk`, type: 'arraybuffer' },
  { url: `fishes/ani/splash.png`, type: 'image' },
  { url: `fishes/ani/fishrod_new.sk`, type: 'arraybuffer' },
  { url: `fishes/ani/fishrod_new.png`, type: 'image' },
  { url: `fishes/ani/tropical_gain.sk`, type: 'arraybuffer' },
  { url: `fishes/ani/tropical_gain.png`, type: 'image' },
  { url: `panel/ani/vs.sk`, type: 'arraybuffer' },
  { url: `panel/ani/vs.png`, type: 'image' },
  { url: `panel/ani/waiting.sk`, type: 'arraybuffer' },
  { url: `panel/ani/waiting.png`, type: 'image' },
  { url: `panel/bg.png`, type: 'image' },
  { url: 'atlas/game.atlas', type: 'atlas' },
  { url: 'atlas/panel.atlas', type: 'atlas' },
  { url: 'atlas/popup.atlas', type: 'atlas' },
  { url: 'atlas/guide.atlas', type: 'atlas' },
  { url: 'bitmapFont/org_slackey.fnt', type: 'font', name: 'org_slackey' },
  { url: 'bitmapFont/org_slackey.png', type: 'image' },
  // { url: 'bitmapFont/font_return.png', type: 'image', name: 'font_return' },
];
