/* eslint-disable */
export default {
  return_game: '返回游戏',
  player: '玩家',
  get_price: '获奖',
  bet_num: '投币 {num}',
  no_data: '暂时没有记录',
  bet_record: '投币记录',
  round_title: 'No. {num}',
  price: '中奖: 0',
  price_num: '中奖 {num}',
  my_bet: '我：{num}',
  dog_win: '狗胜',
  cat_win: '猫胜',
  draw: '平局',
  fish_total: '鱼总数：{num}',
  round_hash: '本局哈希：{hash}',
  hash_code: '哈希值：{hash}',
  copy: '复制',
  paste: '粘贴',
  copy_success: '复制成功',
  bet_title: '我的投币',
  settle: '结算',
  verify: '验证',
  declare_verify: '我们确保所有的数据都是公平的；你可以随时输入哈希 来查询对应的游戏结果（不包含投币返奖结果）',
  setting_voice: '音量设置',
  music: '音乐',
  sound: '音效',
  play: '开始游戏',
  view_trend: '走势',
  guess_winner: '猜胜负',
  guess_number: '猜数字',
  winner_subject: '请选择您要支持的一方，为他加油吧！',
  number_subject: '请选择双方钓鱼总数或区间！',
  guide_tips_1: '1. 选择币种',
  guide_tips_2: '2. 选择投币金额，投币给您认为会获胜的一方。',
  guide_tips_3: '3. 若您投币的一方与获胜一方相同，您将获得对应奖励。',
  tips_hash_code: '哈希值输入错误，无法查询',
  tips_paste: '长按粘贴',
  tips_net_timeout: '网络链接错误',
  error_1: '很抱歉，服务器异常，您可以稍后刷新重试',
  error_31: '房间维护中',
  error_32: '未登录，请重新登录',
  error_34_0: '戏未开始，不能投币',
  error_34: '投币已结束',
  error_36: '押注金额超出上限',
  tips: '提示',
  error_39: '投币数量已达上限',
  msg_repeatedly_login: '您的账号已在其他设备登录',
  confirm: '确定',
  login: '登录',
  login_to_view: '登录查看',
  error_33: '你的操作太频繁了',
  error_37: '房间准备中，请稍后',
  no_search_data: '无记录',
  error_3: '账户余额不足',
  error_34_: '戏未开始，不能投币',
  trend_tab_1: '胜负走势',
  trend_tab_2: '总数走势',
  recently_recorded: '显示最近50条记录',
};
