/* eslint-disable */
export default {
  return_game: 'Return to game',
  player: 'Player',
  get_price: 'Win prize',
  bet_num: 'Bet {num}',
  no_data: 'Currently no history',
  bet_record: 'Betting history',
  round_title: 'No. {num}',
  price: 'Prize{0}',
  price_num: 'Prize {num}',
  my_bet: 'My: {num}',
  dog_win: 'Dog Win',
  cat_win: 'Cat Win',
  draw: 'Draw',
  fish_total: 'Fishing amount:{num}',
  round_hash: 'Hash for this game:{hash}',
  hash_code: 'Hash value:{hash}',
  copy: 'Copy',
  paste: 'Paste',
  bet_title: 'My bets',
  settle: 'Settlements',
  verify: 'Verify',
  declare_verify:
    'We guarantee that all data is fair; you can look up results by entering the corresponding hash value (This does not include the results of prizes returned from bets)',
  setting_voice: 'Volume setting',
  music: 'Music',
  sound: 'Sound Effect',
  play: 'Start game',
  view_trend: 'Trend',
  guess_winner: 'Guess Single',
  guess_number: 'Guess Number',
  winner_subject: 'Chose the side you want to support, and cheer for them!',
  number_subject: 'Please choose the total amount or interval of fishing for both sides',
  guide_tips_1: '1.Choose currency',
  guide_tips_2: '2.Choose the amount you want to bet, and bet on the side who you think will win.',
  guide_tips_3: '3.If you place your bet on the winning side, you will receive certain prizes.',
  error_1: 'Sorry, there has been a server error, please refresh and try again',
  error_31: 'Room is undergoing maintenance',
  error_32: 'You are not logged in, please log in first.',
  error_34_1: "Game haven’t start, can't bet now",
  error_36: 'Amount of bet exceeded the maximum limit',
  copy_success: 'Copy Successful',
  tips_hash_code: 'Hash value input error, unable to run query',
  tips_paste: 'Long click paste',
  tips_net_timeout: 'Network connection error',
  error_34: 'Betting has ended',
  tips: 'Reminder',
  error_34_0: 'Game has not yet started, unable to place bet',
  error_39: 'The number of bets has reached the maximum limit',
  msg_repeatedly_login: 'You are already logged into your account on another device',
  confirm: 'Confirm',
  login: 'Login',
  login_to_view: 'Login to view',
  error_1_: 'System is under maintaining',
  error_34_: 'Game has not yet started, unable to place bet',
  error_33: 'Operation done too frequently',
  error_37: 'The room is not yet ready, please wait',
  no_search_data: 'No history',
  error_3: 'Insufficient balance',
  trend_tab_1: 'Win-loss trend',
  trend_tab_2: 'Total trend',
  recently_recorded: 'Display the most recent 50 records',
};
