/* eslint-disable */
export default {
  return_game: 'Quay lại game',
  player: 'Người chơi',
  get_price: 'Nhận thưởng',
  bet_num: 'Đặt cược {num}',
  no_data: 'Chưa có lịch sử',
  no_search_data: 'Không lịch sử',
  bet_record: 'Lịch sử đặt cược',
  round_title: 'No. {num}',
  price: 'Thưởng: 0',
  price_num: 'Thưởng {num}',
  my_bet: 'Tôi: {num}',
  dog_win: 'Chó thắng',
  cat_win: 'Mèo thắng',
  draw: 'Hòa',
  fish_total: 'Tổng số cá: {num}',
  round_hash: 'Hash hiệp này: {hash}',
  hash_code: 'Giá trị Hash: {hash}',
  copy: 'Sao chép',
  paste: 'Dán',
  copy_success: 'Sao chép xong',
  bet_title: 'Đặt cược của tôi',
  settle: 'Thanh toán',
  verify: 'Xác minh',
  declare_verify:
    'Chúng tôi đảm bảo sự công bằng toàn bộ dữ liệu; bạn có thể nhập Hash mọi lúc để xem kết quả game tương ứng (không gồm kết quả hoàn trả đặt cược)\r\n',
  setting_voice: 'Cài đặt âm lượng',
  music: 'Âm nhạc',
  sound: 'Âm thanh',
  play: 'Bắt đầu chơi',
  view_trend: 'Xu hướng',
  guess_winner: 'Đoán thắng thua',
  guess_number: 'Đoán số',
  winner_subject: 'Xin chọn bên bạn ủng hộ, cổ vũ họ!',
  number_subject: 'Xin chọn tổng số câu cá hoặc khoảng thời gian của 2 bên!',
  guide_tips_1: '1. Chọn coin',
  guide_tips_2: '2. Chọn số tiền đặt cược, đặt cho bên bạn cho rằng sẽ thắng.',
  guide_tips_3:
    '3. Nếu bên bạn đặt cược giống với bên giành thắng, bạn sẽ nhận được phần thưởng tương ứng.',
  tips_hash_code: 'Nhập giá trị Hash bị lỗi, không thể tìm',
  tips_paste: 'Giữ để dán',
  tips_net_timeout: 'Liên kết mạng bị lỗi',
  error_1:
    'Rất tiếc, máy chủ bất thường, bạn có thể đợi để làm mới và thử lại ',
  error_3: 'Số dư tài khoản không đủ',
  error_31: 'Đang bảo trì phòng',
  error_32: 'Chưa đăng nhập, xin đăng nhập lại',
  error_33: 'Thao tác của bạn quá nhiều',
  error_34_: 'Kịch chưa bắt đầu, không thể đặt cược',
  error_34: 'Đặt cược đã kết thúc',
  error_36: 'Số tiền cược vượt quá giới hạn',
  error_37: 'Đang chuẩn bị phòng, vui lòng đợi',
  tips: 'Nhắc',
  error_39: 'Số lượng đặt cược đã đạt đến giới hạn',
  msg_repeatedly_login: 'Tài khoản của bạn đã đăng nhập trên thiết bị khác',
  confirm: 'Xác nhận',
  login: 'Đăng nhập',
  login_to_view: 'Đăng nhập để xem',
  trend_tab_1: 'Xu hướng thắng thua',
  trend_tab_2: 'Tổng xu hướng',
  recently_recorded: '50 lịch sử sử gần đây',
};
