/* eslint-disable */
export default {
  return_game: 'ゲームに戻る',
  player: 'プレーヤー',
  get_price: '賞品を獲得する',
  bet_num: '賭け {num}',
  no_data: '現在、記録はありません',
  bet_record: '賭けの記録',
  round_title: 'No. {num}',
  price: '賞品{0}',
  price_num: '賞品 {num}',
  my_bet: '私：{num}',
  dog_win: '犬が勝つ',
  cat_win: '猫が勝つ',
  draw: 'ドロー',
  fish_total: '釣り量：{num}',
  round_hash: 'このゲームハッシュ：{hash}',
  hash_code: 'ゲームハッシュ：{hash}',
  copy: 'コピー',
  paste: 'ペースト',
  bet_title: '私の賭け',
  settle: '決済',
  verify: '確認',
  declare_verify:
    'すべてのデータが公正であることを保証します。 ハッシュ値を入力していつでもゲーム結果を確認できます（賭け後の賞金は含まれていません）',
  setting_voice: 'ボリュームセット',
  music: '音楽',
  sound: '効果音',
  play: 'ゲームをスタート',
  view_trend: '傾向',
  guess_winner: '勝者を推測する',
  guess_number: '数を推測する',
  winner_subject: 'あなたがサポートしたい側を選んで、それを応援してください',
  number_subject: '両側の合計釣り量の間隔を選択してください',
  guide_tips_1: '1.通貨を選択します',
  guide_tips_2: '2.賭け金額を選択し、勝つと思う側に賭けます',
  guide_tips_3: '3.勝者側に賭けると、一定の賞金がもらえます',
  error_1: '申し訳ありませんが、サーバーが異常です。更新して後で再試行できます',
  error_2: '残高不足です',
  error_31: '部屋はメンテナンス中です',
  error_32: 'まだログインしていませんので、まずはログインしてください。',
  error_34_1: 'ゲームが始まっていない、今は賭けられない',
  error_36: 'ベット額が制限を超えています',
  copy_success: 'コピーできた',
  tips_hash_code: 'ハッシュ値の入力が間違いないましたが、クエリできません',
  tips_paste: '長押しして貼り付けます',
  tips_net_timeout: 'ネットワークに異常があります。もう一度お試しください',
  error_34: '投入は終わりました',
  tips: 'プロンプト',
  error_34_0: 'ゲームが始まっていない、今は賭けられない',
  error_39: 'ベット数が上限に達しました',
  msg_repeatedly_login: 'アカウントはすでに別のデバイスにログインしています',
  confirm: '確認',
  login: 'ログイン',
  login_to_view: 'ログイン',
  error_1_: 'システムはメンテナンス中です',
  error_34_: 'ゲームが始まっていない、今は投入できない',
  error_33: 'あなたの操作はあまりにも頻繁です',
  error_37: '部屋は準備中です、お待ちください',
  no_search_data: '記録なし',
  error_3: '残高不足です',
  trend_tab_1: '勝負の趨勢',
  trend_tab_2: '総数の趨勢',
  recently_recorded: '最後の50レコードを表示する',
};
