/* eslint-disable */
export default {
  return_game: '게임으로 돌아간다',
  player: '유저',
  get_price: '상을 받았다',
  bet_num: '내기 {num}',
  no_data: '현재는 기록이 없습니다',
  bet_record: '코인 투입 기록',
  round_title: 'No. {num}',
  price: '당첨:0',
  price_num: '당첨 {num}',
  my_bet: '나: {num}',
  dog_win: '개 승리',
  cat_win: '고양이 승리',
  draw: '무승부',
  fish_total: '물고시 총수:{num}',
  round_hash: '이번판 해스: {hash}',
  hash_code: '해시 값: {hash}',
  copy: '복사',
  paste: '붙여넣기',
  bet_title: '나의 코인',
  settle: '결산',
  verify: '검증',
  declare_verify:
    '모든 데이터는 공평하다는 것은 우리가 확실히 보증할 수 있고, 아무때나 해시를 입력하여 그에 맞는 게임 결과를 조회할 수 있다.( 코인 리턴 결과는 제외)',
  setting_voice: '음량 설정',
  music: '음악',
  sound: '효과음',
  play: '게임 스타트',
  view_trend: '경향',
  guess_winner: '승부 맞추기',
  guess_number: '숫자 맞추기',
  winner_subject: '당신이 지지하는 편을 선택하고 그를 응원 해주세요.',
  number_subject: '양쪽의 낚시 총수와 구역을 선택해주세요.',
  guide_tips_1: '1.코인 종류 선택',
  guide_tips_2:
    '2.코인 투입 금액을 선택하여 우승할 것 같은 편에 동전을 투입해주세요.',
  guide_tips_3:
    '3.만약 당신이 동전 투입한 편이 우승하면 그에 맞는 보상을 받게 됩니다.',
  error_1:
    '죄송합니다. 서버가 비정상입니다. 새로 고침하고 나중에 다시 시도하세요.',
  error_2: '계정 잔액 부족',
  error_31: '룸 점검중',
  error_32: '미등록, 다시 로그인 해주세요.',
  error_34_1: '게임 시작 되지 않았습니다, 코인 투입 불가합니다',
  error_36: '베팅 금액이 상한을 초과했습니다',
  copy_success: '복사성공',
  tips_hash_code: '해시값 입력 오류. 검색 불가',
  tips_paste: '붙여 넣으려면 길게 누르세요',
  tips_net_timeout: '불안정한 네트워크입니다. 다시 시도하세요.',
  error_34: '베팅이 끝났습니다',
  tips: '알림',
  error_34_0: '게임 시작 되지 않았습니다, 코인 투입 불가합니다',
  error_39: '베팅 횟수가 상한선에 도달했습니다',
  msg_repeatedly_login: '귀하의 계정은 다른 장치에서 로그인되었습니다',
  confirm: '확인',
  login: '로그인',
  login_to_view: '로그인 후 확인',
  error_1_: '시스템 점검중',
  error_34_: '게임 시작 되지 않았습니다, 코인 투입 불가합니다',
  error_33: '수술이 너무 잦습니다',
  error_37: '방이 준비 중입니다. 기다려주세요',
  no_search_data: '어떤 기록도 없다',
  error_3: '계정 잔액 부족',
  trend_tab_1: '승패의 흐름',
  trend_tab_2: '총수의 흐름',
  recently_recorded: '최근 50건 기록을 보기',
};
