/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import I18nComponent from "./common/I18nComponent"
import TrendSelector from "./modules/popup/TrendSelector"
import NewGuideFooter from "./modules/panels/NewGuideFooter"
import UserInfo from "./modules/panels/UserInfo"
import Trends from "./modules/panels/Trends"
import Counter from "./modules/panels/Counter"
import Footer from "./modules/panels/Footer"
import MenuPanel from "./modules/panels/MenuPanel"
import CurrencyPanel from "./modules/panels/CurrencyPanel"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1624;
    static scaleMode:string="fixedwidth";
    static screenMode:string="vertical";
    static alignV:string="middle";
    static alignH:string="left";
    static startScene:any="Loading.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("common/I18nComponent.ts",I18nComponent);
        reg("modules/popup/TrendSelector.ts",TrendSelector);
        reg("modules/panels/NewGuideFooter.ts",NewGuideFooter);
        reg("modules/panels/UserInfo.ts",UserInfo);
        reg("modules/panels/Trends.ts",Trends);
        reg("modules/panels/Counter.ts",Counter);
        reg("modules/panels/Footer.ts",Footer);
        reg("modules/panels/MenuPanel.ts",MenuPanel);
        reg("modules/panels/CurrencyPanel.ts",CurrencyPanel);
    }
}
GameConfig.init();